name: Release Charts

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Shubham Tatvamasi"
          git config user.email "shubhamtatvamasi@gmail.com"

      - name: Add helm repo
        run: helm repo add orc8r https://shubhamtatvamasi.github.io/magma-charts-8-8-2022

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
